global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
 - job_name: 'product-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.1.71:8091']
        labels:
          application: 'product-service'

