global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
 
  - job_name: 'cliente-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'cliente-service'

  - job_name: 'eureka-registry-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'eureka-registry-service'

  - job_name: 'gateway-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'gateway-service'

  - job_name: 'inventario-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'inventario-service'

  - job_name: 'proveedores-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'proveedores-service'
          
  - job_name: 'ventas-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'ventas-service'
  